@startuml SystemMap

title SystemMap Tablet Mode 2

state "Idle" as idle

state "Adding Variable \n / Adding Stock" as addNode
state "Editing Variable \n / Editing Stock" as editNode
state "Moving Variable \n / Moving Stock" as moveNode : move

[*] -> idle

idle -up-> addNode : trigger add Variable \n / trigger add Stock
idle -up-> moveNode : down \n on Variable \n / Stock
idle -up-> editNode : click \n on Variable \n / Stock
editNode --> idle : click \n on background
addNode -> editNode : click \n on background \n : createVariable() \n / createStock()
moveNode -left> editNode : up


state "Adding Link" as addLink
state "Dragging Link" as dragLink : move
state "Editing Link" as editLink
state "Shaping Link" as shapeLink : move

idle -up-> addLink : trigger add Link
addLink -up-> dragLink : down \n on Variable \n or Stock
dragLink --> editLink : up \n on Variable \n or Valve
idle -up-> editLink : click \n on Link
editLink --> idle : click \n on background
idle -up-> shapeLink : down \n on Link
shapeLink -> editLink : up

state "Adding Flow" as addFlow
state "Dragging Flow" as dragFlow : move
state "Editing Flow" as editFlow
state "Shaping Flow" as shapeFlow : move

idle --> addFlow : trigger add Flow
addFlow --> dragFlow : down \n on Stock \n or background
dragFlow -up-> editFlow : up \n on background \n or Stock
idle --> editFlow : click \n on Flow
editFlow -up-> idle : click \n on background
idle --> shapeFlow : down \n on Valve \n or Source \n or Sink
shapeFlow -> editFlow : up

@enduml
